apiVersion: v1
kind: Service
metadata:
  name: {{ include "issassist.name" . }}
  labels:
    {{- include "issassist.labels" . | nindent 4 }}
spec:
  type: {{ .Values.issassist.frontend.service.type }}
  ports:
    - name: http
      port: {{ .Values.issassist.frontend.service.port }}
      targetPort: nginx
      protocol: TCP
  selector:
    {{- include "issassist.selectorLabels" . | nindent 4 }}
