# Generated by Django 3.2.8 on 2021-12-08 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssSys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_id', models.SmallIntegerField(default=0)),
                ('update_datetime', models.DateTimeField(auto_now_add=True)),
                ('isssys_version', models.CharField(blank=True, default='0.0.1-Build-0001', max_length=24)),
                ('total_updates', models.SmallIntegerField(default=0)),
                ('security_updates', models.SmallIntegerField(default=0)),
                ('priority1_updates', models.SmallIntegerField(default=0)),
                ('priority2_updates', models.SmallIntegerField(default=0)),
                ('priority3_updates', models.SmallIntegerField(default=0)),
                ('priority4_updates', models.SmallIntegerField(default=0)),
                ('priority5_updates', models.SmallIntegerField(default=0)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
